# Generated by Django 6.0.7 on 2026-07-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_options_remove_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_cart_product_per_user',
        ),
    ]
